### ISSUE TITLE
Unsubscribe to stream

### ISSUE THREAD

**Issue by jgraef** [nimiq/jsonrpc#2]
1. Instead of returning a `BoxStream` return something that is `Stream`, but also has a `unsubscribe` method. This should tell the server to stop sending notifications and terminate the stream.
2. How does the client know which method to call for unsubscribe?

**Comment by sisou** [comment]
Regarding 2.) currently an ID is returned as the result of the subscribe call. This ID is included in the streamed events, as the events are simply called 'subscription'. So I'd say there could be a general 'unsubscribe' method that takes the ID as the argument.
